name: smart_ashtray_app
description: Smart Ashtray Flutter app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.0.0
  dio_cookie_manager: ^3.0.0
  cookie_jar: ^4.0.0
  flutter_secure_storage: ^9.0.0
  flutter_dotenv: ^5.0.0
  riverpod: ^2.0.0
  go_router: ^14.0.0
  web_socket_channel: ^2.0.0
  fl_chart: ^0.69.0

flutter:
  uses-material-design: true
  assets:
    - .env
